# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/FrmMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmMain(object):
    def setupUi(self, FrmMain):
        FrmMain.setObjectName("FrmMain")
        FrmMain.resize(741, 464)
        self.verticalLayout = QtWidgets.QVBoxLayout(FrmMain)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(FrmMain)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.lEditOldOriginFilePath = QtWidgets.QLineEdit(self.frame)
        self.lEditOldOriginFilePath.setMinimumSize(QtCore.QSize(0, 30))
        self.lEditOldOriginFilePath.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lEditOldOriginFilePath.setObjectName("lEditOldOriginFilePath")
        self.gridLayout.addWidget(self.lEditOldOriginFilePath, 0, 1, 1, 1)
        self.lEditOldTransFilePath = QtWidgets.QLineEdit(self.frame)
        self.lEditOldTransFilePath.setMinimumSize(QtCore.QSize(0, 30))
        self.lEditOldTransFilePath.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lEditOldTransFilePath.setObjectName("lEditOldTransFilePath")
        self.gridLayout.addWidget(self.lEditOldTransFilePath, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(120, 30))
        self.label.setMaximumSize(QtCore.QSize(120, 30))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(120, 30))
        self.label_2.setMaximumSize(QtCore.QSize(120, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.btnFileExplorerOldOrigin = QtWidgets.QPushButton(self.frame)
        self.btnFileExplorerOldOrigin.setMinimumSize(QtCore.QSize(0, 30))
        self.btnFileExplorerOldOrigin.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnFileExplorerOldOrigin.setObjectName("btnFileExplorerOldOrigin")
        self.gridLayout.addWidget(self.btnFileExplorerOldOrigin, 0, 2, 1, 1)
        self.btnFileExplorerOldTrans = QtWidgets.QPushButton(self.frame)
        self.btnFileExplorerOldTrans.setMinimumSize(QtCore.QSize(0, 30))
        self.btnFileExplorerOldTrans.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnFileExplorerOldTrans.setObjectName("btnFileExplorerOldTrans")
        self.gridLayout.addWidget(self.btnFileExplorerOldTrans, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(120, 30))
        self.label_3.setMaximumSize(QtCore.QSize(120, 30))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lEditNewOriginFilePath = QtWidgets.QLineEdit(self.frame)
        self.lEditNewOriginFilePath.setMinimumSize(QtCore.QSize(0, 30))
        self.lEditNewOriginFilePath.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lEditNewOriginFilePath.setObjectName("lEditNewOriginFilePath")
        self.gridLayout.addWidget(self.lEditNewOriginFilePath, 2, 1, 1, 1)
        self.btnFileExplorerNewOrigin = QtWidgets.QPushButton(self.frame)
        self.btnFileExplorerNewOrigin.setMinimumSize(QtCore.QSize(0, 30))
        self.btnFileExplorerNewOrigin.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnFileExplorerNewOrigin.setObjectName("btnFileExplorerNewOrigin")
        self.gridLayout.addWidget(self.btnFileExplorerNewOrigin, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(FrmMain)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(FrmMain)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lEditOutputFileName = QtWidgets.QLineEdit(self.frame_3)
        self.lEditOutputFileName.setMinimumSize(QtCore.QSize(0, 30))
        self.lEditOutputFileName.setObjectName("lEditOutputFileName")
        self.horizontalLayout.addWidget(self.lEditOutputFileName)
        self.btnGenerate = QtWidgets.QPushButton(self.frame_3)
        self.btnGenerate.setMinimumSize(QtCore.QSize(120, 40))
        self.btnGenerate.setMaximumSize(QtCore.QSize(120, 40))
        self.btnGenerate.setObjectName("btnGenerate")
        self.horizontalLayout.addWidget(self.btnGenerate)
        self.btnExit = QtWidgets.QPushButton(self.frame_3)
        self.btnExit.setMinimumSize(QtCore.QSize(120, 40))
        self.btnExit.setMaximumSize(QtCore.QSize(120, 40))
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout.addWidget(self.btnExit)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(FrmMain)
        QtCore.QMetaObject.connectSlotsByName(FrmMain)

    def retranslateUi(self, FrmMain):
        _translate = QtCore.QCoreApplication.translate
        FrmMain.setWindowTitle(_translate("FrmMain", "SC2Translator"))
        self.label.setText(_translate("FrmMain", "旧原文文件"))
        self.label_2.setText(_translate("FrmMain", "旧翻译文件"))
        self.btnFileExplorerOldOrigin.setText(_translate("FrmMain", "..."))
        self.btnFileExplorerOldTrans.setText(_translate("FrmMain", "..."))
        self.label_3.setText(_translate("FrmMain", "新原文文件"))
        self.btnFileExplorerNewOrigin.setText(_translate("FrmMain", "..."))
        self.plainTextEdit.setPlainText(_translate("FrmMain", "注:\n"
"--使用--\n"
"可以没有旧原文文件，但没有时无法检测原文是否有更新\n"
"\n"
"--生成--\n"
"新增词条后会被添加 // newEntry\n"
"原文有改动的词条后会被添加 // originEntryHasBeenModified\n"
"\n"
"--注意事项--\n"
"这是一个不稳定的测试版\n"
"\n"
"--作者--\n"
"Elliott"))
        self.label_4.setText(_translate("FrmMain", "生成文件名:"))
        self.lEditOutputFileName.setText(_translate("FrmMain", "Output.txt"))
        self.btnGenerate.setText(_translate("FrmMain", "生成"))
        self.btnExit.setText(_translate("FrmMain", "退出"))
